### ISSUE TITLE
Improve ability to detect ranges

### ISSUE THREAD

**Issue by diasdavid** [nodesecurity/nodesecurity-www#25]
david-dm.org is able to detect vulnerabilities in ranges that `nsp` currently doesn't. We can see this happening on https://github.com/nodesecurity/nodesecurity-blog

LOG of conversation with Alan: https://gist.github.com/diasdavid/4a94e8871c5bfe76133f

**Comment by evilpacket** [comment]
Closing this as we are changing out the API and if it's still an issue it can be re-raised.
