### ISSUE TITLE
Separate advisories and logic into its own module

### ISSUE THREAD

**Issue by davglass** [nodesecurity/nodesecurity-www#26]
It would be nice if the advisory data and the logic powering the API from that data was pulled out into another module so that others can use the data :smile:

**Comment by totherik** [comment]
Hah, I *just* (as in Friday) wrote a short script to download, extract, and cache the advisory data to run some internal tooling. Having it as a proper API would be great. Let me know if I can help.

**Comment by diasdavid** [comment]
We've a couple of modules that extra some of the `nsp` functionality so that other modules can use it, namely:

- https://github.com/nodesecurity/nsp-api
- https://github.com/nodesecurity/nsp-audit-shrinkwrap

Does this help?

**Comment by davglass** [comment]
The idea is that we want to expose our own api so that we don't blast your server with requests. If I were to add this to my build system I would kill your host in a matter of minutes :smile:

**Comment by totherik** [comment]
Here's a thing I wrote if it helps in the interim. Have a TODO to persist the data across restarts, and if your organization burns through unauthenticated GitHub API requests from the same IP I may need to add auth, but for me, for now, it works...
- https://www.npmjs.com/package/advisor
- https://github.com/totherik/advisor

**Comment by evilpacket** [comment]
The new API will replace the old markdown / repository method that we currently have in place to support the new client that's. We MAY in the future have a repo with advisories in it that are public, but that won't be a for a while

However if you look close you will see a offline mode for the new cli that will allow closing of the advisories for use. That might be of use until we can work something out. Closing for now.
