### ISSUE TITLE
No charset in headers and HTML

### ISSUE THREAD

**Issue by rsp** [nodesecurity/nodesecurity-www#37]
There is no character encoding defined in the HTTP headers and in the HTML. It results in the "™" character not displaying correctly:
![charset-before](https://cloud.githubusercontent.com/assets/119231/6679918/cad50a6c-cc4f-11e4-856a-af6b6937f799.png)

Also the charset can be guessed as UTF-7 in old browsers (see: [UTF-7 encoding](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#UTF-7_encoding) on [The Open Web Application Security Project](https://www.owasp.org/index.php/Main_Page) and [UTF-7 XSS Cheat Sheet](http://openmya.hacker.jp/hasegawa/security/utf7cs.html) by Yosuke HASEGAWA).

**Comment by rsp** [comment]
It is fixed by the pull request #36.

**Comment by evilpacket** [comment]
Thx!

**Comment by rsp** [comment]
Closed by merging pull request #36
